insert into category (description) values ('american');
insert into category (description) values ('indian');
insert into category (description) values ('italian');
insert into category (description) values ('mexican');
insert into unit_of_measure (uom) values ('teaspoon');
insert into unit_of_measure (uom) values ('tablespoon');
insert into unit_of_measure (uom) values ('cup');
insert into unit_of_measure (uom) values ('pinch');
insert into unit_of_measure (uom) values ('ounce');